name: "${project.name}"
version: "${project.version}"
api-version: 1.17
main: craftcourier.spigot.Main
website: "https://github.com/sebastianjnuwu/craftcourier"
depend: [nLogin]
author: [
  "Sebastian Jn <sebastianjnuwu@gmail.com>",
  ]
description: "${project.description}"