name: "KettraShop"
version: "11.08.2024"
api-version: 1.17
main: kettraworld.com.BR
depend: [nLogin]
website: "https://github.com/kettraworld/KettraShop"
author: "Sebastian Jn <sebastianjnuwu@gmail.com>"
description: "Delivery of the products compared in the store..."
commands:
  kw:
    permision: "kw.reload"
    description: "Command used no KettraShop plugin"
    usage: /kw <reload>